name: iris-classifier-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - scikit-learn
  - flask
  - gunicorn
  - joblib
  - pip:
      - azureml-defaults
